import { EVStation } from '@/types';

export const EV_STATIONS_DATA: EVStation[] = [
  {
    id: 'ev-1',
    name: 'Tata Power EZ Charge - DLF CyberCity',
    network: 'Tata Power EZ Charge',
    address: 'DLF CyberCity Hub, Building 10, Gurugram, Haryana',
    coordinates: { latitude: 28.4952, longitude: 77.0891 },
    distanceKm: 1.8,
    availablePorts: 5,
    totalPorts: 6,
    maxPowerKw: 60,
    connectors: ['CCS2', 'Type2_AC', 'GB/T'],
    costPerKwh: 18.5,
  },
  {
    id: 'ev-2',
    name: 'Ather Grid Fast Charger - Indiranagar',
    network: 'Ather Grid',
    address: '100 Feet Road, HAL 2nd Stage, Indiranagar, Bengaluru',
    coordinates: { latitude: 12.9716, longitude: 77.6412 },
    distanceKm: 2.4,
    availablePorts: 4,
    totalPorts: 4,
    maxPowerKw: 22,
    connectors: ['2W_3W_Swap', 'Type2_AC'],
    costPerKwh: 14.0,
  },
  {
    id: 'ev-3',
    name: 'Jio-bp pulse Mega Hub - Aerocity',
    network: 'Jio-bp pulse',
    address: 'Worldmark 1, Aerocity, New Delhi, Delhi 110037',
    coordinates: { latitude: 28.5505, longitude: 77.1215 },
    distanceKm: 3.2,
    availablePorts: 8,
    totalPorts: 12,
    maxPowerKw: 120,
    connectors: ['CCS2', 'CHAdeMO', 'Type2_AC'],
    costPerKwh: 21.0,
  },
  {
    id: 'ev-4',
    name: 'Magenta ChargeGrid - Bandra Kurla Complex',
    network: 'Magenta Power',
    address: 'G Block, BKC, Bandra East, Mumbai, Maharashtra 400051',
    coordinates: { latitude: 19.0657, longitude: 77.8682 },
    distanceKm: 4.1,
    availablePorts: 3,
    totalPorts: 6,
    maxPowerKw: 50,
    connectors: ['CCS2', 'GB/T'],
    costPerKwh: 19.0,
  },
  {
    id: 'ev-5',
    name: 'Statiq Ultra EV Hub - Sector 29',
    network: 'Statiq',
    address: 'Near HUDA City Centre Metro, Sector 29, Gurugram',
    coordinates: { latitude: 28.4635, longitude: 77.0601 },
    distanceKm: 5.0,
    availablePorts: 6,
    totalPorts: 8,
    maxPowerKw: 150,
    connectors: ['CCS2', 'Type2_AC', '2W_3W_Swap'],
    costPerKwh: 17.5,
  },
];
